{% set name = "yaspin" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/yaspin/yaspin-{{ version }}.tar.gz
  sha256: 7b97c7e257ec598f98cef9878e038bfa619ceb54ac31d61d8ead2b3128f8d7c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - termcolor >=2.2.0,<2.4.0

test:
  imports:
    - yaspin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pavdmyt/yaspin
  summary: Yet Another Terminal Spinner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
    - claudiushaag
